### ISSUE TITLE
Implement local override of ASN descriptions

### ISSUE THREAD

**Issue by coolparadox** [turbobytes/geoipdb#13]
Sometimes the ASN description returned by third party databases is not optimal.

This is a request to make geoipdb capable of maintain a database of local descriptions of given ASNs.

- These descriptions would take precedence as return values of LookupAsn().
- There must be API endpoints for adding and removing ASN descriptions.

**Comment by sajal** [comment]
I suggest using `geoipdb` collection in `dnsdist` database. 
The propose following object format :-

    {"_id": "AS555", name: "The description"}

The geoipdb lib would take a `*mgo.Collection` during init, and if not `nil` then it will do the lookups against mongo.
