### ISSUE TITLE
Implement method for retrieval of all ASN description overrides

### ISSUE THREAD

**Issue by coolparadox** [turbobytes/geoipdb#16]
Name sugestion: `OverridesList()`
Returns a map containing ASNs and descriptions

Reference: [pulse#14](/turbobytes/pulse/issues/14)

**Comment by coolparadox** [comment]
Update: `OverridesList()` will return a slice of `geoipdb.AsnOverride` instead of a map.

This is enables direct parsing by mongo.

**Comment by sajal** [comment]
+1 for slice. Its easier to work with in UI code as well.
