### ISSUE TITLE
Timeout accesses to external services

### ISSUE THREAD

**Issue by coolparadox** [turbobytes/geoipdb#5]
Blocking calls that access external services (currently ipinfo.io) must have a timeout so callers are not indefinitely locked.

This issue is a request for having timeouts implemented when the library reaches external services.

**Comment by sajal** [comment]
I suggest 5-second timeout to start with.

**Comment by coolparadox** [comment]
I intend to implement a timeout parameter in NewHandler() with millisecond granularity, defaulting to 5 seconds if user passes a null value.

This parameter will be used in all external queries -- ipinfo and cymru. (Libgeoip is a local access, so as I see no timeout protection is required.)

**Comment by sajal** [comment]
+1
